kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vote-pv-claim
  namespace: vote
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi